/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  cev_rz_os                              */
/*      FILE         :  cev_rz_os.c                            */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/
#include <typedefine.h>
#include <iodefine.h>

extern void initialize_page_table(uint32_t* pTable);

int main(void) {
	uint32_t *page_table = (uint32_t *)0x20080000;
	initialize_page_table(page_table);
    while(1) {
    	int i = 0;

    	// P7_8 LED1(Red)
    	// P7_9 LED2(Red)
    	GPIOPMC7	= 0x0000;	// Port Mode Control Register
    	GPIOPM7		= 0x0000;	// Port Mode Register
    	GPIOP7		= 0x0000;	// Port Register
    	uint16_t val = 0x300;
    	// P7_8,P7_9
        while(1) {
        	for(i = 0; i < 1000000; i++);
    		GPIOP7		^= val;	// Port Register
    		// TODO: add application code here
        }
    }
	return 0;
}
